sudo: required
addons:
  chrome: stable
dist: trusty

language: node_js
node_js:
  - "8"

before_script:
  - yarn global add @angular/cli
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - ng test ngx-chat-xmpp --code-coverage --watch=false --browsers Chrome_ci

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
